PCBNEW-LibModule-V1  
# encoding utf-8
Units mm
$INDEX
TSSOP-56_3
$EndINDEX
$MODULE TSSOP-56_3
Po 0 0 0 15 00000000 00000000 ~~
Li TSSOP-56_3
Cd <b>TSSOP-56_3</b><p>Auto generated by <i>make-symbol-device-package-bsdl.ulp Rev. 43</i><br>
Sc 00000000
At SMD
Op 0 0 0
.SolderMask 0
.SolderPaste 0
T0 -0.075 -8.27 1 1 0 0.05 N V 21 "TSSOP-56_3"
T1 -0.075 7.77 0.787402 0.787402 0 0.05 N V 21 "VAL**"
DA 0 -6.8984 0.6 -6.8984 1800 0.2032 21
DS -2.9484 6.8984 2.9484 6.8984 0.2032 21
DS 2.9484 6.8984 2.9484 -6.8984 0.2032 21
DS 2.9484 -6.8984 -2.9484 -6.8984 0.2032 21
DS -2.9484 -6.8984 -2.9484 6.8984 0.2032 21
DP 0 0 0 0 4 0.381 24
Dl -4.075 -6.875
Dl -3.05 -6.875
Dl -3.05 -6.625
Dl -4.075 -6.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -6.375
Dl -3.05 -6.375
Dl -3.05 -6.125
Dl -4.075 -6.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 -5.875
Dl -3.05 -5.875
Dl -3.05 -5.625
Dl -4.075 -5.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -5.375
Dl -3.05 -5.375
Dl -3.05 -5.125
Dl -4.075 -5.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 -4.875
Dl -3.05 -4.875
Dl -3.05 -4.625
Dl -4.075 -4.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -4.375
Dl -3.05 -4.375
Dl -3.05 -4.125
Dl -4.075 -4.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 -3.875
Dl -3.05 -3.875
Dl -3.05 -3.625
Dl -4.075 -3.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -3.375
Dl -3.05 -3.375
Dl -3.05 -3.125
Dl -4.075 -3.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 -2.875
Dl -3.05 -2.875
Dl -3.05 -2.625
Dl -4.075 -2.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -2.375
Dl -3.05 -2.375
Dl -3.05 -2.125
Dl -4.075 -2.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 -1.875
Dl -3.05 -1.875
Dl -3.05 -1.625
Dl -4.075 -1.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -1.375
Dl -3.05 -1.375
Dl -3.05 -1.125
Dl -4.075 -1.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 -0.875
Dl -3.05 -0.875
Dl -3.05 -0.625
Dl -4.075 -0.625
DP 0 0 0 0 4 0.381 24
Dl -4.075 -0.375
Dl -3.05 -0.375
Dl -3.05 -0.125
Dl -4.075 -0.125
DP 0 0 0 0 4 0.381 24
Dl -4.075 0.125
Dl -3.05 0.125
Dl -3.05 0.375
Dl -4.075 0.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 0.625
Dl -3.05 0.625
Dl -3.05 0.875
Dl -4.075 0.875
DP 0 0 0 0 4 0.381 24
Dl -4.075 1.125
Dl -3.05 1.125
Dl -3.05 1.375
Dl -4.075 1.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 1.625
Dl -3.05 1.625
Dl -3.05 1.875
Dl -4.075 1.875
DP 0 0 0 0 4 0.381 24
Dl -4.075 2.125
Dl -3.05 2.125
Dl -3.05 2.375
Dl -4.075 2.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 2.625
Dl -3.05 2.625
Dl -3.05 2.875
Dl -4.075 2.875
DP 0 0 0 0 4 0.381 24
Dl -4.075 3.125
Dl -3.05 3.125
Dl -3.05 3.375
Dl -4.075 3.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 3.625
Dl -3.05 3.625
Dl -3.05 3.875
Dl -4.075 3.875
DP 0 0 0 0 4 0.381 24
Dl -4.075 4.125
Dl -3.05 4.125
Dl -3.05 4.375
Dl -4.075 4.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 4.625
Dl -3.05 4.625
Dl -3.05 4.875
Dl -4.075 4.875
DP 0 0 0 0 4 0.381 24
Dl -4.075 5.125
Dl -3.05 5.125
Dl -3.05 5.375
Dl -4.075 5.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 5.625
Dl -3.05 5.625
Dl -3.05 5.875
Dl -4.075 5.875
DP 0 0 0 0 4 0.381 24
Dl -4.075 6.125
Dl -3.05 6.125
Dl -3.05 6.375
Dl -4.075 6.375
DP 0 0 0 0 4 0.381 24
Dl -4.075 6.625
Dl -3.05 6.625
Dl -3.05 6.875
Dl -4.075 6.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 6.625
Dl 4.075 6.625
Dl 4.075 6.875
Dl 3.05 6.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 6.125
Dl 4.075 6.125
Dl 4.075 6.375
Dl 3.05 6.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 5.625
Dl 4.075 5.625
Dl 4.075 5.875
Dl 3.05 5.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 5.125
Dl 4.075 5.125
Dl 4.075 5.375
Dl 3.05 5.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 4.625
Dl 4.075 4.625
Dl 4.075 4.875
Dl 3.05 4.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 4.125
Dl 4.075 4.125
Dl 4.075 4.375
Dl 3.05 4.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 3.625
Dl 4.075 3.625
Dl 4.075 3.875
Dl 3.05 3.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 3.125
Dl 4.075 3.125
Dl 4.075 3.375
Dl 3.05 3.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 2.625
Dl 4.075 2.625
Dl 4.075 2.875
Dl 3.05 2.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 2.125
Dl 4.075 2.125
Dl 4.075 2.375
Dl 3.05 2.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 1.625
Dl 4.075 1.625
Dl 4.075 1.875
Dl 3.05 1.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 1.125
Dl 4.075 1.125
Dl 4.075 1.375
Dl 3.05 1.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 0.625
Dl 4.075 0.625
Dl 4.075 0.875
Dl 3.05 0.875
DP 0 0 0 0 4 0.381 24
Dl 3.05 0.125
Dl 4.075 0.125
Dl 4.075 0.375
Dl 3.05 0.375
DP 0 0 0 0 4 0.381 24
Dl 3.05 -0.375
Dl 4.075 -0.375
Dl 4.075 -0.125
Dl 3.05 -0.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -0.875
Dl 4.075 -0.875
Dl 4.075 -0.625
Dl 3.05 -0.625
DP 0 0 0 0 4 0.381 24
Dl 3.05 -1.375
Dl 4.075 -1.375
Dl 4.075 -1.125
Dl 3.05 -1.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -1.875
Dl 4.075 -1.875
Dl 4.075 -1.625
Dl 3.05 -1.625
DP 0 0 0 0 4 0.381 24
Dl 3.05 -2.375
Dl 4.075 -2.375
Dl 4.075 -2.125
Dl 3.05 -2.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -2.875
Dl 4.075 -2.875
Dl 4.075 -2.625
Dl 3.05 -2.625
DP 0 0 0 0 4 0.381 24
Dl 3.05 -3.375
Dl 4.075 -3.375
Dl 4.075 -3.125
Dl 3.05 -3.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -3.875
Dl 4.075 -3.875
Dl 4.075 -3.625
Dl 3.05 -3.625
DP 0 0 0 0 4 0.381 24
Dl 3.05 -4.375
Dl 4.075 -4.375
Dl 4.075 -4.125
Dl 3.05 -4.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -4.875
Dl 4.075 -4.875
Dl 4.075 -4.625
Dl 3.05 -4.625
DP 0 0 0 0 4 0.381 24
Dl 3.05 -5.375
Dl 4.075 -5.375
Dl 4.075 -5.125
Dl 3.05 -5.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -5.875
Dl 4.075 -5.875
Dl 4.075 -5.625
Dl 3.05 -5.625
DP 0 0 0 0 4 0.381 24
Dl 3.05 -6.375
Dl 4.075 -6.375
Dl 4.075 -6.125
Dl 3.05 -6.125
DP 0 0 0 0 4 0.381 24
Dl 3.05 -6.875
Dl 4.075 -6.875
Dl 4.075 -6.625
Dl 3.05 -6.625
$PAD
Sh "1" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -6.75
$EndPAD
$PAD
Sh "2" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -6.25
$EndPAD
$PAD
Sh "3" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -5.75
$EndPAD
$PAD
Sh "4" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -5.25
$EndPAD
$PAD
Sh "5" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -4.75
$EndPAD
$PAD
Sh "6" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -4.25
$EndPAD
$PAD
Sh "7" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -3.75
$EndPAD
$PAD
Sh "8" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -3.25
$EndPAD
$PAD
Sh "9" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -2.75
$EndPAD
$PAD
Sh "10" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -2.25
$EndPAD
$PAD
Sh "11" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -1.75
$EndPAD
$PAD
Sh "12" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -1.25
$EndPAD
$PAD
Sh "13" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -0.75
$EndPAD
$PAD
Sh "14" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 -0.25
$EndPAD
$PAD
Sh "15" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 0.25
$EndPAD
$PAD
Sh "16" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 0.75
$EndPAD
$PAD
Sh "17" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 1.25
$EndPAD
$PAD
Sh "18" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 1.75
$EndPAD
$PAD
Sh "19" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 2.25
$EndPAD
$PAD
Sh "20" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 2.75
$EndPAD
$PAD
Sh "21" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 3.25
$EndPAD
$PAD
Sh "22" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 3.75
$EndPAD
$PAD
Sh "23" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 4.25
$EndPAD
$PAD
Sh "24" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 4.75
$EndPAD
$PAD
Sh "25" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 5.25
$EndPAD
$PAD
Sh "26" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 5.75
$EndPAD
$PAD
Sh "27" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 6.25
$EndPAD
$PAD
Sh "28" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po -3.775 6.75
$EndPAD
$PAD
Sh "29" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 6.75
$EndPAD
$PAD
Sh "30" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 6.25
$EndPAD
$PAD
Sh "31" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 5.75
$EndPAD
$PAD
Sh "32" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 5.25
$EndPAD
$PAD
Sh "33" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 4.75
$EndPAD
$PAD
Sh "34" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 4.25
$EndPAD
$PAD
Sh "35" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 3.75
$EndPAD
$PAD
Sh "36" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 3.25
$EndPAD
$PAD
Sh "37" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 2.75
$EndPAD
$PAD
Sh "38" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 2.25
$EndPAD
$PAD
Sh "39" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 1.75
$EndPAD
$PAD
Sh "40" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 1.25
$EndPAD
$PAD
Sh "41" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 0.75
$EndPAD
$PAD
Sh "42" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 0.25
$EndPAD
$PAD
Sh "43" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -0.25
$EndPAD
$PAD
Sh "44" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -0.75
$EndPAD
$PAD
Sh "45" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -1.25
$EndPAD
$PAD
Sh "46" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -1.75
$EndPAD
$PAD
Sh "47" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -2.25
$EndPAD
$PAD
Sh "48" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -2.75
$EndPAD
$PAD
Sh "49" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -3.25
$EndPAD
$PAD
Sh "50" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -3.75
$EndPAD
$PAD
Sh "51" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -4.25
$EndPAD
$PAD
Sh "52" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -4.75
$EndPAD
$PAD
Sh "53" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -5.25
$EndPAD
$PAD
Sh "54" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -5.75
$EndPAD
$PAD
Sh "55" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -6.25
$EndPAD
$PAD
Sh "56" R 1.3 0.3 0 0 0
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 3.775 -6.75
$EndPAD
$PAD
Sh "57" R 6.5 3.7 0 0 2700
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 0 0
$EndPAD
$PAD
Sh "58" R 0.4 0.65 0 0 2700
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 0 -3.45
$EndPAD
$PAD
Sh "59" R 0.4 0.65 0 0 2700
At SMD N 00888000
.SolderMask 0
.SolderPaste 0
Ne 0 ""
Po 0 3.45
$EndPAD
$EndMODULE TSSOP-56_3
